package com.example.myapplication.activities

import android.os.Build
import android.os.Bundle
import android.text.Html
import com.yookoo.discoveraddis.databinding.ActivityTermsBinding
import com.example.myapplication.ui.base.BindingActivity
import com.yookoo.discoveraddis.R


class PrivacyAndTerms : BindingActivity<ActivityTermsBinding> () {
    override fun getLayout(): Int {
        return  R.layout.activity_terms
    }

    var privacy_data: String ="<h1>Privacy Policy</h1>\n\n" +
            "<p>Last updated: June 06, 2023</p>\n" +
            "<p>This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.</p>\n" +
            "<p>We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.\n" +
            "<h1>Interpretation and Definitions</h1>\n" +
            "<h2>Interpretation</h2>\n" +
            "<p>The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.</p>\n" +
            "<h2>Definitions</h2>\n" +
            "<p>For the purposes of this Privacy Policy:</p>\n" +
            "<ul>\n" +
            "<li>\n" +
            "<p><strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.</p>\n" +
            "</li>\n" +
            "<li>\n" +
            "<p><strong>Affiliate</strong> means an entity that controls, is controlled by or is under common control with a party, where &quot;control&quot; means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</p>\n" +
            "</li>\n" +
            "<li>\n" +
            "<p><strong>Application</strong> refers to Discover Addis Ababa, the software program provided by the Company.</p>\n" +
            "</li>\n" +
            "<li>\n" +
            "<p><strong>Company</strong> (referred to as either &quot;the Company&quot;, &quot;We&quot;, &quot;Us&quot; or &quot;Our&quot; in this Agreement) refers to Wos International Business Group PLC, Ethiopia, Addis Ababa.</p>\n" +
            "</li>\n" +
            "<li>\n" +
            "<p><strong>Country</strong> refers to:  Ethiopia</p>\n" +
            "</li>\n" +
            "<li>\n" +
            "<p><strong>Device</strong> means any device that can access the Service such as a computer, a cellphone or a digital tablet.</p>\n" +
            "</li>\n" +
            "<li>\n" +
            "<p><strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.</p>\n" +
            "</li>\n" +
            "<li>\n" +
            "<p><strong>Service</strong> refers to the Application.</p>\n" +
            "</li>\n" +
            "<li>\n" +
            "<p><strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.</p>\n" +
            "</li>\n" +
            "<li>\n" +
            "<p><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</p>\n" +
            "</li>\n" +
            "<li>\n" +
            "<p><strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</p>\n" +
            "</li>\n" +
            "</ul>\n" +
            "<h1>Collecting and Using Your Personal Data</h1>\n" +
            "<h2>Types of Data Collected</h2>\n" +
            "<h3>Personal Data</h3>\n" +
            "<p>While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:</p>\n" +
            "<ul>\n" +
            "<li>\n" +
            "<p>Email address</p>\n" +
            "</li>\n" +
            "<li>\n" +
            "<p>First name and last name</p>\n" +
            "</li>\n" +
            "<li>\n" +
            "<p>Phone number</p>\n" +
            "</li>\n" +
            "<li>\n" +
            "<p>Address, State, Province, ZIP/Postal code, City</p>\n" +
            "</li>\n" +
            "<li>\n" +
            "<p>Usage Data</p>\n" +
            "</li>\n" +
            "</ul>\n" +
            "<h3>Usage Data</h3>\n" +
            "<p>Usage Data is collected automatically when using the Service.</p>\n" +
            "<p>Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.</p>\n" +
            "<p>When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.</p>\n" +
            "<p>We may also collect information that Your browser sends whenever You visit our Service or when You access the Service by or through a mobile device.</p>\n" +
            "<h3>Information Collected while Using the Application</h3>\n" +
            "<p>While using Our Application, in order to provide features of Our Application, We may collect, with Your prior permission:</p>\n" +
            "<ul>\n" +
            "<li>\n" +
            "<p>Information regarding your location</p>\n" +
            "</li>\n" +
            "<li>\n" +
            "<p>Pictures and other information from your Device's camera and photo library</p>\n" +
            "</li>\n" +
            "</ul>\n" +
            "<p>We use this information to provide features of Our Service, to improve and customize Our Service. The information may be uploaded to the Company's servers and/or a Service Provider's server or it may be simply stored on Your device.</p>\n" +
            "<p>You can enable or disable access to this information at any time, through Your Device settings.</p>\n" +
            "<h2>Use of Your Personal Data</h2>\n" +
            "<p>The Company may use Personal Data for the following purposes:</p>\n" +
            "<ul>\n" +
            "<li>\n" +
            "<p><strong>To provide and maintain our Service</strong>, including to monitor the usage of our Service.</p>\n" +
            "</li>\n" +
            "<li>\n" +
            "<p><strong>To manage Your Account:</strong> to manage Your registration as a user of the Service. The Personal Data You provide can give You access to different functionalities of the Service that are available to You as a registered user.</p>\n" +
            "</li>\n" +
            "<li>\n" +
            "<p><strong>For the performance of a contract:</strong> the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased or of any other contract with Us through the Service.</p>\n" +
            "</li>\n" +
            "<li>\n" +
            "<p><strong>To contact You:</strong> To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication, such as a mobile application's push notifications regarding updates or informative communications related to the functionalities, products or contracted services, including the security updates, when necessary or reasonable for their implementation.</p>\n" +
            "</li>\n" +
            "<li>\n" +
            "<p><strong>To provide You</strong> with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless You have opted not to receive such information.</p>\n" +
            "</li>\n" +
            "<li>\n" +
            "<p><strong>To manage Your requests:</strong> To attend and manage Your requests to Us.</p>\n" +
            "</li>\n" +
            "<li>\n" +
            "<p><strong>For business transfers:</strong> We may use Your information to evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of Our assets, whether as a going concern or as part of bankruptcy, liquidation, or similar proceeding, in which Personal Data held by Us about our Service users is among the assets transferred.</p>\n" +
            "</li>\n" +
            "<li>\n" +
            "<p><strong>For other purposes</strong>: We may use Your information for other purposes, such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns and to evaluate and improve our Service, products, services, marketing and your experience.</p>\n" +
            "</li>\n" +
            "</ul>\n" +
            "<p>We may share Your personal information in the following situations:</p>\n" +
            "<ul>\n" +
            "<li><strong>With Service Providers:</strong> We may share Your personal information with Service Providers to monitor and analyze the use of our Service,  to contact You.</li>\n" +
            "<li><strong>For business transfers:</strong> We may share or transfer Your personal information in connection with, or during negotiations of, any merger, sale of Company assets, financing, or acquisition of all or a portion of Our business to another company.</li>\n" +
            "<li><strong>With Affiliates:</strong> We may share Your information with Our affiliates, in which case we will require those affiliates to honor this Privacy Policy. Affiliates include Our parent company and any other subsidiaries, joint venture partners or other companies that We control or that are under common control with Us.</li>\n" +
            "<li><strong>With business partners:</strong> We may share Your information with Our business partners to offer You certain products, services or promotions.</li>\n" +
            "<li><strong>With other users:</strong> when You share personal information or otherwise interact in the public areas with other users, such information may be viewed by all users and may be publicly distributed outside.</li>\n" +
            "<li><strong>With Your consent</strong>: We may disclose Your personal information for any other purpose with Your consent.</li>\n" +
            "</ul>\n" +
            "<h2>Retention of Your Personal Data</h2>\n" +
            "<p>The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.</p>\n" +
            "<p>The Company will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period of time, except when this data is used to strengthen the security or to improve the functionality of Our Service, or We are legally obligated to retain this data for longer time periods.</p>\n" +
            "<h2>Transfer of Your Personal Data</h2>\n" +
            "<p>Your information, including Personal Data, is processed at the Company's operating offices and in any other places where the parties involved in the processing are located. It means that this information may be transferred to — and maintained on — computers located outside of Your state, province, country or other governmental jurisdiction where the data protection laws may differ than those from Your jurisdiction.</p>\n" +
            "<p>Your consent to this Privacy Policy followed by Your submission of such information represents Your agreement to that transfer.</p>\n" +
            "<p>The Company will take all steps reasonably necessary to ensure that Your data is treated securely and in accordance with this Privacy Policy and no transfer of Your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of Your data and other personal information.</p>\n" +
            "<h2>Delete Your Personal Data</h2>\n" +
            "<p>You have the right to delete or request that We assist in deleting the Personal Data that We have collected about You.</p>\n" +
            "<p>Our Service may give You the ability to delete certain information about You from within the Service.</p>\n" +
            "<p>You may update, amend, or delete Your information at any time by signing in to Your Account, if you have one, and visiting the account settings section that allows you to manage Your personal information. You may also contact Us to request access to, correct, or delete any personal information that You have provided to Us.</p>\n" +
            "<p>Please note, however, that We may need to retain certain information when we have a legal obligation or lawful basis to do so.</p>\n" +
            "<h2>Disclosure of Your Personal Data</h2>\n" +
            "<h3>Business Transactions</h3>\n" +
            "<p>If the Company is involved in a merger, acquisition or asset sale, Your Personal Data may be transferred. We will provide notice before Your Personal Data is transferred and becomes subject to a different Privacy Policy.</p>\n" +
            "<h3>Law enforcement</h3>\n" +
            "<p>Under certain circumstances, the Company may be required to disclose Your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency).</p>\n" +
            "<h3>Other legal requirements</h3>\n" +
            "<p>The Company may disclose Your Personal Data in the good faith belief that such action is necessary to:</p>\n" +
            "<ul>\n" +
            "<li>Comply with a legal obligation</li>\n" +
            "<li>Protect and defend the rights or property of the Company</li>\n" +
            "<li>Prevent or investigate possible wrongdoing in connection with the Service</li>\n" +
            "<li>Protect the personal safety of Users of the Service or the public</li>\n" +
            "<li>Protect against legal liability</li>\n" +
            "</ul>\n" +
            "<h2>Security of Your Personal Data</h2>\n" +
            "<p>The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.</p>\n" +
            "<h1>Detailed Information on the Processing of Your Personal Data</h1>\n" +
            "<p>The Service Providers We use may have access to Your Personal Data. These third-party vendors collect, store, use, process and transfer information about Your activity on Our Service in accordance with their Privacy Policies.</p>\n" +
            "<h2>Usage, Performance and Miscellaneous</h2>\n" +
            "<p>We may use third-party Service Providers to provide better improvement of our Service.</p>\n" +
            "<ul>\n" +
            "<li>\n" +
            "<p><strong>Google Places</strong></p>\n" +
            "<p>Google Places is a service that returns information about places using HTTP requests. It is operated by Google</p>\n" +
            "<p>Google Places service may collect information from You and from Your Device for security purposes.</p>\n" +
            "<p>The information gathered by Google Places is held in accordance with the Privacy Policy of Google: <a href=\"https://www.google.com/intl/en/policies/privacy/\" rel=\"external nofollow noopener\" target=\"_blank\">https://www.google.com/intl/en/policies/privacy/</a></p>\n" +
            "</li>\n" +
            "</ul>\n" +
            "<h1>Children's Privacy</h1>\n" +
            "<p>Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us. If We become aware that We have collected Personal Data from anyone under the age of 13 without verification of parental consent, We take steps to remove that information from Our servers.</p>\n" +
            "<p>If We need to rely on consent as a legal basis for processing Your information and Your country requires consent from a parent, We may require Your parent's consent before We collect and use that information.</p>\n" +
            "<h1>Links to Other Websites</h1>\n" +
            "<p>Our Service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be directed to that third party's site. We strongly advise You to review the Privacy Policy of every site You visit.</p>\n" +
            "<p>We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.</p>\n" +
            "<h1>Changes to this Privacy Policy</h1>\n" +
            "<p>We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.</p>\n" +
            "<p>We will let You know via email and/or a prominent notice on Our Service, prior to the change becoming effective and update the &quot;Last updated&quot; date at the top of this Privacy Policy.</p>\n" +
            "<p>You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.</p>\n" +
            "<h1>Contact Us</h1>\n" +
            "<p>If you have any questions about this Privacy Policy, You can contact us:</p>"



    var terms_data: String="<h2><strong>Terms and Conditions</strong></h2>\n\n" +
            "\n" +
            "<p>Welcome to Discover Addis Ababa!</p>\n" +
            "\n" +
            "<p>These terms and conditions outline the rules and regulations for the use of Wos International Business Group PLC's Website, located at Discover Addis Ababa.</p>\n" +
            "\n" +
            "<p>By accessing this website we assume you accept these terms and conditions. Do not continue to use Discover Addis Ababa if you do not agree to take all of the terms and conditions stated on this page.</p>\n" +
            "\n" +
            "<p>The following terminology applies to these Terms and Conditions, Privacy Statement and Disclaimer Notice and all Agreements: \"Client\", \"You\" and \"Your\" refers to you, the person log on this website and compliant to the Company's terms and conditions. \"The Company\", \"Ourselves\", \"We\", \"Our\" and \"Us\", refers to our Company. \"Party\", \"Parties\", or \"Us\", refers to both the Client and ourselves. All terms refer to the offer, acceptance and consideration of payment necessary to undertake the process of our assistance to the Client in the most appropriate manner for the express purpose of meeting the Client's needs in respect of provision of the Company's stated services, in accordance with and subject to, prevailing law of et. Any use of the above terminology or other words in the singular, plural, capitalization and/or he/she or they, are taken as interchangeable and therefore as referring to same.</p>\n" +
            "\n" +
            "<h3><strong>Cookies</strong></h3>\n" +
            "\n" +
            "<p>We employ the use of cookies. By accessing Discover Addis Ababa, you agreed to use cookies in agreement with the Wos International Business Group PLC's Privacy Policy. </p>\n" +
            "\n" +
            "<p>Most interactive websites use cookies to let us retrieve the user's details for each visit. Cookies are used by our website to enable the functionality of certain areas to make it easier for people visiting our website. Some of our affiliate/advertising partners may also use cookies.</p>\n" +
            "\n" +
            "<h3><strong>License</strong></h3>\n" +
            "\n" +
            "<p>Unless otherwise stated, Wos International Business Group PLC and/or its licensors own the intellectual property rights for all material on Discover Addis Ababa. All intellectual property rights are reserved. You may access this from Discover Addis Ababa for your own personal use subjected to restrictions set in these terms and conditions.</p>\n" +
            "\n" +
            "<p>You must not:</p>\n" +
            "<ul>\n" +
            "    <li>Republish material from Discover Addis Ababa</li>\n" +
            "    <li>Sell, rent or sub-license material from Discover Addis Ababa</li>\n" +
            "    <li>Reproduce, duplicate or copy material from Discover Addis Ababa</li>\n" +
            "    <li>Redistribute content from Discover Addis Ababa</li>\n" +
            "</ul>\n" +
            "\n" +
            "<p>This Agreement shall begin on the date hereof. Our Terms and Conditions were created with the help of the <a href=\"https://www.termsandconditionsgenerator.com/\">Free Terms and Conditions Generator</a>.</p>\n" +
            "\n" +
            "<p>Parts of this website offer an opportunity for users to post and exchange opinions and information in certain areas of the website. Wos International Business Group PLC does not filter, edit, publish or review Comments prior to their presence on the website. Comments do not reflect the views and opinions of Wos International Business Group PLC,its agents and/or affiliates. Comments reflect the views and opinions of the person who post their views and opinions. To the extent permitted by applicable laws, Wos International Business Group PLC shall not be liable for the Comments or for any liability, damages or expenses caused and/or suffered as a result of any use of and/or posting of and/or appearance of the Comments on this website.</p>\n" +
            "\n" +
            "<p>Wos International Business Group PLC reserves the right to monitor all Comments and to remove any Comments which can be considered inappropriate, offensive or causes breach of these Terms and Conditions.</p>\n" +
            "\n" +
            "<p>You warrant and represent that:</p>\n" +
            "\n" +
            "<ul>\n" +
            "    <li>You are entitled to post the Comments on our website and have all necessary licenses and consents to do so;</li>\n" +
            "    <li>The Comments do not invade any intellectual property right, including without limitation copyright, patent or trademark of any third party;</li>\n" +
            "    <li>The Comments do not contain any defamatory, libelous, offensive, indecent or otherwise unlawful material which is an invasion of privacy</li>\n" +
            "    <li>The Comments will not be used to solicit or promote business or custom or present commercial activities or unlawful activity.</li>\n" +
            "</ul>\n" +
            "\n" +
            "<p>You hereby grant Wos International Business Group PLC a non-exclusive license to use, reproduce, edit and authorize others to use, reproduce and edit any of your Comments in any and all forms, formats or media.</p>\n" +
            "\n" +
            "<h3><strong>Hyperlinking to our Content</strong></h3>\n" +
            "\n" +
            "<p>The following organizations may link to our Website without prior written approval:</p>\n" +
            "\n" +
            "<ul>\n" +
            "    <li>Government agencies;</li>\n" +
            "    <li>Search engines;</li>\n" +
            "    <li>News organizations;</li>\n" +
            "    <li>Online directory distributors may link to our Website in the same manner as they hyperlink to the Websites of other listed businesses; and</li>\n" +
            "    <li>System wide Accredited Businesses except soliciting non-profit organizations, charity shopping malls, and charity fundraising groups which may not hyperlink to our Web site.</li>\n" +
            "</ul>\n" +
            "\n" +
            "<p>These organizations may link to our home page, to publications or to other Website information so long as the link: (a) is not in any way deceptive; (b) does not falsely imply sponsorship, endorsement or approval of the linking party and its products and/or services; and (c) fits within the context of the linking party's site.</p>\n" +
            "\n" +
            "<p>We may consider and approve other link requests from the following types of organizations:</p>\n" +
            "\n" +
            "<ul>\n" +
            "    <li>commonly-known consumer and/or business information sources;</li>\n" +
            "    <li>dot.com community sites;</li>\n" +
            "    <li>associations or other groups representing charities;</li>\n" +
            "    <li>online directory distributors;</li>\n" +
            "    <li>internet portals;</li>\n" +
            "    <li>accounting, law and consulting firms; and</li>\n" +
            "    <li>educational institutions and trade associations.</li>\n" +
            "</ul>\n" +
            "\n" +
            "<p>We will approve link requests from these organizations if we decide that: (a) the link would not make us look unfavorably to ourselves or to our accredited businesses; (b) the organization does not have any negative records with us; (c) the benefit to us from the visibility of the hyperlink compensates the absence of Wos International Business Group PLC; and (d) the link is in the context of general resource information.</p>\n" +
            "\n" +
            "<p>These organizations may link to our home page so long as the link: (a) is not in any way deceptive; (b) does not falsely imply sponsorship, endorsement or approval of the linking party and its products or services; and (c) fits within the context of the linking party's site.</p>\n" +
            "\n" +
            "<p>If you are one of the organizations listed in paragraph 2 above and are interested in linking to our website, you must inform us by sending an e-mail to Wos International Business Group PLC. Please include your name, your organization name, contact information as well as the URL of your site, a list of any URLs from which you intend to link to our Website, and a list of the URLs on our site to which you would like to link. Wait 2-3 weeks for a response.</p>\n" +
            "\n" +
            "<p>Approved organizations may hyperlink to our Website as follows:</p>\n" +
            "\n" +
            "<ul>\n" +
            "    <li>By use of our corporate name; or</li>\n" +
            "    <li>By use of the uniform resource locator being linked to; or</li>\n" +
            "    <li>By use of any other description of our Website being linked to that makes sense within the context and format of content on the linking party's site.</li>\n" +
            "</ul>\n" +
            "\n" +
            "<p>No use of Wos International Business Group PLC's logo or other artwork will be allowed for linking absent a trademark license agreement.</p>\n" +
            "\n" +
            "<h3><strong>iFrames</strong></h3>\n" +
            "\n" +
            "<p>Without prior approval and written permission, you may not create frames around our Webpages that alter in any way the visual presentation or appearance of our Website.</p>\n" +
            "\n" +
            "<h3><strong>Content Liability</strong></h3>\n" +
            "\n" +
            "<p>We shall not be hold responsible for any content that appears on your Website. You agree to protect and defend us against all claims that is rising on your Website. No link(s) should appear on any Website that may be interpreted as libelous, obscene or criminal, or which infringes, otherwise violates, or advocates the infringement or other violation of, any third party rights.</p>\n" +
            "\n" +
            "<h3><strong>Reservation of Rights</strong></h3>\n" +
            "\n" +
            "<p>We reserve the right to request that you remove all links or any particular link to our Website. You approve to immediately remove all links to our Website upon request. We also reserve the right to amen these terms and conditions and it's linking policy at any time. By continuously linking to our Website, you agree to be bound to and follow these linking terms and conditions.</p>\n" +
            "\n" +
            "<h3><strong>Removal of links from our website</strong></h3>\n" +
            "\n" +
            "<p>If you find any link on our Website that is offensive for any reason, you are free to contact and inform us any moment. We will consider requests to remove links but we are not obligated to or so or to respond to you directly.</p>\n" +
            "\n" +
            "<p>We do not ensure that the information on this website is correct, we do not warrant its completeness or accuracy; nor do we promise to ensure that the website remains available or that the material on the website is kept up to date.</p>\n" +
            "\n" +
            "<h3><strong>Disclaimer</strong></h3>\n" +
            "\n" +
            "<p>To the maximum extent permitted by applicable law, we exclude all representations, warranties and conditions relating to our website and the use of this website. Nothing in this disclaimer will:</p>\n" +
            "\n" +
            "<ul>\n" +
            "    <li>limit or exclude our or your liability for death or personal injury;</li>\n" +
            "    <li>limit or exclude our or your liability for fraud or fraudulent misrepresentation;</li>\n" +
            "    <li>limit any of our or your liabilities in any way that is not permitted under applicable law; or</li>\n" +
            "    <li>exclude any of our or your liabilities that may not be excluded under applicable law.</li>\n" +
            "</ul>\n" +
            "\n" +
            "<p>The limitations and prohibitions of liability set in this Section and elsewhere in this disclaimer: (a) are subject to the preceding paragraph; and (b) govern all liabilities arising under the disclaimer, including liabilities arising in contract, in tort and for breach of statutory duty.</p>\n" +
            "\n" +
            "<p>As long as the website and the information and services on the website are provided free of charge, we will not be liable for any loss or damage of any nature.</p>\n"



    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)


        val intent = intent
        val privacy = intent.getStringExtra("type")


        if (privacy.equals("privacy")){
            viewBinding.title.text = if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.N) {
                Html.fromHtml(privacy_data, Html.FROM_HTML_MODE_COMPACT)
            } else {
                Html.fromHtml(privacy_data)
            }

        }else if (privacy.equals("terms")){
            viewBinding.title.text = if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.N) {
                Html.fromHtml(terms_data, Html.FROM_HTML_MODE_COMPACT)
            } else {
                Html.fromHtml(terms_data)
            }

        }else if (privacy.equals("app_info")){
            viewBinding.title.setText("App Info\n\n" +
                    "The purpose of the app\n" +
                    "Addis Ababa is the capital of Ethiopia and the largest city in East Africa. It is a bustling metropolis with a rich history and culture. There are many things to see and do in Addis Ababa, from visiting historical sites to shopping in the markets.\n" +
                    "\n" +
                    "A smart tourism app for Addis Ababa would be a great way to help visitors find their way around the city and discover all that it has to offer. The app could include features such as a map of the city, information on attractions and events, and a way to book tours and activities.\n" +
                    "\n" +
                    "The app could also be used to provide information on the city's history and culture. This would be a valuable resource for visitors who want to learn more about Addis Ababa.\n" +
                    "\n" +
                    "Overall, a smart tourism app for Addis Ababa would be a great way to help visitors make the most of their trip to the city. It would provide them with information and resources that would make their visit more enjoyable and memorable.\n" +
                    "\n" +
                    "Current features\n" +
                    "•\tAdd/capture businesses, institutions, companies and tourist attraction locations\n" +
                    "•\tSearch and locate businesses, institutions, companies and tourist attraction locations\n" +
                    "\n" +
                    "Upcoming features\n" +
                    "•\tA map of the city with points of interest marked.\n" +
                    "•\tDetailed Information on attractions and events \n" +
                    "•\tA way to book tours, hotels and activities\n" +
                    "•\tInformation on the city’s history and culture\n" +
                    "•\tA way to communicate with other visitors\n" +
                    "•\tA way to get help in case of an emergency\n" +
                    "•\tInformation on water, electricity and traffic of different areas in Addis")

        }else if (privacy.equals("fAndQ")){
            viewBinding.title.setText("Q: What is a smart tourism app?\n\n" +
                    "A: A smart tourism app is an app designed to help tourists plan and organize their trips more effectively. It can provide useful information such as tourist attractions, restaurants, and hotels in a given area, as well as providing maps and directions to help with navigation. It can also provide flight and accommodation booking services. \n" +
                    "\n" +
                    "Q: What are some of the features of a smart tourism app?\n\n" +
                    "A: Features of a smart tourism app typically include the ability to search for attractions and destinations, book flights and accommodation, plan routes and trips, access maps and directions, and research local culture and events. It may also include features such as currency converters and weather forecasts. \n" +
                    "\n" +
                    "Q: How does a smart tourism app benefit travelers?\n\n" +
                    "A: A smart tourism app can save travelers time and money by helping them plan and organize their trips more effectively. It can provide useful information such as tourist attractions, restaurants, and hotels in a given area, as well as providing maps and directions to help with navigation. It can also provide flight and accommodation booking services, currency converters, and weather forecasts.\n" +
                    "\n" +
                    "Can discover addis ababa be used in conjunction with other products or services?\n" +
                    " What is the pricing structure for discover addis ababa and are there any discounts available?\n" +
                    "Is there a money-back guarantee or return policy for discover addis ababa\n" +
                    "Can I get assistance with setting up and using discover addis ababa account?\n" +
                    "What type of support and customer service does discover addis ababa offer?\n" +
                    "How does discover addis ababa compare to similar products in the market?\n" +
                    "\n")


        }

        viewBinding.ivBack.setOnClickListener {
            finish()
        }
    }


}